version: '3'

services:
    db:
        image: mysql:5.7.37
        container_name: laravel-db
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel-db
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "9906:3306"

    redis:
        image: redis:4.0
        container_name: redis
        ports:
            - "6382:6379"

    application:
        build: .
        container_name: monitor-docker
        depends_on:
            - db
            - redis
        volumes:
            - ./:/var/www/html
        ports:
            - 8081:80
        stdin_open: true
        tty: true
